# Generated by Django 5.1.6 on 2025-03-03 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(default='Standard', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('Name', models.CharField(max_length=200)),
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.question')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address_1', models.CharField(default='Unknown', max_length=128, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, default='Unknown', max_length=128, verbose_name="Address cont'd")),
                ('city', models.CharField(default='San Antonio', max_length=64, verbose_name='City')),
                ('State', models.CharField(default='TX', max_length=2)),
                ('zipcode', models.IntegerField()),
                ('languages', models.CharField(choices=[('Spanish', 'Spanish'), ('English', 'English'), ('English and Spanish', 'English Spanish'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='ENG', max_length=19)),
                ('ss_payments', models.BooleanField(default=False, verbose_name='Sliding Scale Payment')),
                ('spiritual', models.BooleanField(default=False)),
                ('lgbtq', models.BooleanField(default=False)),
                ('inpatient', models.BooleanField(default=False)),
                ('outpatient', models.BooleanField(default=False)),
                ('med_assist', models.BooleanField(default=False)),
                ('residential', models.BooleanField(default=False)),
                ('virtual', models.BooleanField(default=False)),
                ('methedone', models.BooleanField(default=False)),
                ('suboxone', models.BooleanField(default=False)),
                ('transportation', models.BooleanField(default=False)),
                ('psych', models.BooleanField(default=False)),
                ('hyperlink', models.URLField(default='https://www.youtube.com/')),
                ('insurance_t', models.ManyToManyField(to='projectApp.insurance')),
            ],
        ),
    ]
