# Generated by Django 5.1.6 on 2025-03-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentcenter',
            name='insurance_t',
        ),
        migrations.AddField(
            model_name='treatmentcenter',
            name='insurances',
            field=models.ManyToManyField(to='projectApp.insurance', verbose_name='Valid Insurances'),
        ),
    ]
