# Generated by Django 5.1.6 on 2025-03-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_remove_treatmentcenter_insurance_t_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='treatmentcenter',
            name='description',
            field=models.CharField(default='Currently Blank: Will be updated', max_length=500),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='treatmentcenter',
            name='languages',
            field=models.CharField(choices=[('Spanish', 'Spanish'), ('English', 'English'), ('English/Spanish', 'English Spanish'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='ENG', max_length=19),
        ),
        migrations.AddField(
            model_name='treatmentcenter',
            name='treat_model',
            field=models.ManyToManyField(to='projectApp.treatment_model'),
        ),
    ]
