# Generated by Django 5.1.6 on 2025-03-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_treatment_model_treatmentcenter_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AlterField(
            model_name='treatmentcenter',
            name='languages',
            field=models.CharField(choices=[('SPAN', 'Spanish'), ('ENG', 'English'), ('ENSP', 'English/Spanish'), ('OTH', 'Other'), ('UNKN', 'Unknown')], default='ENG', max_length=5),
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.question')),
            ],
        ),
    ]
