# Generated by Django 5.1.6 on 2025-04-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_remove_choice_votes_alter_treatmentcenter_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcenter',
            name='active',
            field=models.CharField(choices=[('true', 'Active'), ('false', 'Inactive'), ('null', 'Unkown')], default='null', max_length=10),
        ),
    ]
